var cookies1 = [
  {
    "domain": ".zhipin.com",
    "expirationDate": 1896659740,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__a",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "34479729.1572788848.1580724065.1580806940.4829.15.133.271",
    "id": 1
  },
  {
    "domain": ".zhipin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "__c",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "1580806940",
    "id": 2
  },
  {
    "domain": ".zhipin.com",
    "expirationDate": 1581386141,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__f",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "70a04797b0c8cec85fa564a4fa08d3ab",
    "id": 3
  },
  {
    "domain": ".zhipin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "__g",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "-",
    "id": 4
  },
  {
    "domain": ".zhipin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "__l",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "l=https%3A%2F%2Fwww.zhipin.com%2Fchat%2Fim%3Fmu%3D%252Fbossweb%252Fjoblist.html&r=&friend_source=0&friend_source=0",
    "id": 5
  },
  {
    "domain": ".zhipin.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "Hm_lpvt_194df3105ad7148dcf2b98a91b5e727a",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "1581299741",
    "id": 6
  },
  {
    "domain": ".zhipin.com",
    "expirationDate": 1612835740,
    "hostOnly": false,
    "httpOnly": false,
    "name": "Hm_lvt_194df3105ad7148dcf2b98a91b5e727a",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1580724065,1580806940,1580813150,1580868605",
    "id": 7
  },
  {
    "domain": ".zhipin.com",
    "expirationDate": 1612407492.554504,
    "hostOnly": false,
    "httpOnly": false,
    "name": "lastCity",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "101200100",
    "id": 8
  },
  {
    "domain": ".zhipin.com",
    "expirationDate": 1581793200.738779,
    "hostOnly": false,
    "httpOnly": true,
    "name": "t",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "HGSs00BHhhUsB82h",
    "id": 9
  },
  {
    "domain": ".zhipin.com",
    "expirationDate": 1581793200.738916,
    "hostOnly": false,
    "httpOnly": true,
    "name": "wt",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "HGSs00BHhhUsB82h",
    "id": 10
  },
  {
    "domain": "www.zhipin.com",
    "expirationDate": 1588340884.804887,
    "hostOnly": true,
    "httpOnly": false,
    "name": "_bl_uid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "31knq2k6jdh17dwqt6Cqd58g0I5v",
    "id": 11
  },
  {
    "domain": "www.zhipin.com",
    "hostOnly": true,
    "httpOnly": true,
    "name": "JSESSIONID",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "\"\"",
    "id": 12
  }
];

var cookies2 =
  [
    {
      "domain": ".zhipin.com",
      "expirationDate": 1896230501,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__a",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "34479729.1572788848.1580724065.1580806940.4766.15.70.208",
      "id": 1
    },
    {
      "domain": ".zhipin.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "__c",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "1580806940",
      "id": 2
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1580956799,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__f",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "70a04797b0c8cec85fa564a4fa08d3ab",
      "id": 3
    },
    {
      "domain": ".zhipin.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "__g",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "-",
      "id": 4
    },
    {
      "domain": ".zhipin.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "__l",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "l=https%3A%2F%2Fwww.zhipin.com%2Fchat%2Fim%3Fmu%3D%252Fbossweb%252Fjoblist.html&r=&friend_source=0&friend_source=0",
      "id": 5
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1581100901,
      "hostOnly": false,
      "httpOnly": false,
      "name": "__zp_stoken__",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "e2e31kVrcsCdg3gvvp4n8loDRV64ko2TZsGsLLBfw7bPkNGWfHY4mb3sZYb1GgYjEaDALsE6l3MrGFwF4h6MX4lJuce7Vjughl6lJgDaOSI5XQCa6dgh6RHc4%2BAAR93XFGCX",
      "id": 6
    },
    {
      "domain": ".zhipin.com",
      "hostOnly": false,
      "httpOnly": false,
      "name": "Hm_lpvt_194df3105ad7148dcf2b98a91b5e727a",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": true,
      "storeId": "0",
      "value": "1580870469",
      "id": 7
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1612406469,
      "hostOnly": false,
      "httpOnly": false,
      "name": "Hm_lvt_194df3105ad7148dcf2b98a91b5e727a",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1580724065,1580806940,1580813150,1580868605",
      "id": 8
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1612406404.517754,
      "hostOnly": false,
      "httpOnly": false,
      "name": "lastCity",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "101200100",
      "id": 9
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1581793200.985235,
      "hostOnly": false,
      "httpOnly": true,
      "name": "t",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "xhZGOHneRhnDTVZh",
      "id": 10
    },
    {
      "domain": ".zhipin.com",
      "expirationDate": 1581793200.985343,
      "hostOnly": false,
      "httpOnly": true,
      "name": "wt",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "xhZGOHneRhnDTVZh",
      "id": 11
    },
    {
      "domain": "www.zhipin.com",
      "expirationDate": 1588340884.804887,
      "hostOnly": true,
      "httpOnly": false,
      "name": "_bl_uid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "31knq2k6jdh17dwqt6Cqd58g0I5v",
      "id": 12
    },
    {
      "domain": "www.zhipin.com",
      "hostOnly": true,
      "httpOnly": true,
      "name": "JSESSIONID",
      "path": "/",
      "sameSite": "unspecified",
      "secure": true,
      "session": true,
      "storeId": "0",
      "value": "\"\"",
      "id": 13
    }
  ]
module.exports = {
  cookies1,cookies2
}
